### ISSUE TITLE
Catalog

### ISSUE THREAD

**Issue by nevze** [keizerworks/invoicen#78] opened 2024-12-28 08:14 UTC
### Current Behaviour

code EUNSUPPORTEDPROTOCOL
Unsupported URL Type "catalog:": catalog:

### Expected Behaviour

How to fix this?

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you willing to submit PR?

No

<sub><a href="https://huly.app/guest/keizerworks?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZmYjM4M2YxNDRmNTg1YWU1MTM0YzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2VpemVyd29ya3Mta2VpemVyd29ya3MtNjc2YmIzYzQtNTg1NDc1Mzg4My00NDc3M2YifQ.LnGYvWT9a2s4u1t50enMDc3GRutcXLZs9pR5TGkXzjo">Huly&reg;: <b>INVOI-78</b></a></sub>

**Comment by Sudarsh1010** [comment] 2024-12-28 08:31
not able to reproduce, please provide steps to reproduce this issue

**Comment by Prithviraj2003** [comment] 2024-12-28 09:50
@nevze It seems you're using ` npm `to install packages, but our project uses ` pnpm ` for managing dependencies.
Try running ` pnpm install ` to install dependencies.

**Comment by Prithviraj2003** [comment] 2024-12-28 10:16
@Sudarsh1010 I think we should close this issue.

**Comment by aayushchugh** [comment] 2024-12-28 11:35
@Prithviraj2003 I think it's a bot

**Closed by aayushchugh** 2024-12-28 11:35 UTC
Labels: bug
